#!/bin/bash

PWD="$( pwd )"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

read -p "Are you sure? " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Cleaning backup folder..."
    cd "$SCRIPT_DIR/../backup"
    find . -mindepth 1 -name \* -delete # rm -rf wasn't working here but this does the job.
    cd "$PWD"
fi

echo "Done!"