#!/bin/bash

PWD=$( pwd )
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SOURCE_DIR="/mnt/c/Users/jrose/AppData/Local/FactoryGame/Saved/SaveGames/Computers"

# Create a folder in the repo /drives folder for each computer found in the Satisfactory computers folder.
cd $SOURCE_DIR
DRIVES="$( find . -mindepth 1 -maxdepth 1 -type d | sort -u | cut -c3-34 )"
for DRIVE in $DRIVES
do
    echo "Found drive $DRIVE..."
    mkdir "$SCRIPT_DIR/../drives/$DRIVE" >/dev/null 2>&1
    mkdir "$SCRIPT_DIR/../drives/$DRIVE/tags" >/dev/null 2>&1
    touch "$SCRIPT_DIR/../drives/$DRIVE/tags/.gitkeep"
    mkdir "$SCRIPT_DIR/../drives/$DRIVE/data" >/dev/null 2>&1
    touch "$SCRIPT_DIR/../drives/$DRIVE/data/.gitkeep"
    cp -rf $DRIVE/data/* "$SCRIPT_DIR/../drives/$DRIVE/data" >/dev/null 2>&1
done

cd $PWD

echo "Done!"