#!/bin/bash

PWD="$( pwd )"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DEST_DIR="/mnt/c/Users/jrose/AppData/Local/FactoryGame/Saved/SaveGames/Computers"
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`

# Copy current Satisfactory Ficsit-Networks computer configuration into the backup folder in case anything breaks.
echo "Backing up Satisfactory folder..."
cp -rf "$DEST_DIR" "$SCRIPT_DIR/../backup/$TIMESTAMP"

# Use the find script to sync data from the Satisfactory state.
# This is important to maintain settings of computer systems set up ingame!!!
./find >/dev/null 2>&1

# Delete the existing computer configuration.
echo "Cleaning Satisfactory folder..."
cd "$DEST_DIR"
find . -mindepth 1 -name \* -delete # rm -rf wasn't working here but this does the job.

# Publish the repo drives into the Satisfactory folder.
echo "Publishing computers to Satisfactory folder..."
cp -rf $SCRIPT_DIR/../drives/* "$DEST_DIR"

cd $PWD

echo "Done!"