#!/bin/bash

###################################################################################################
# push
#
# Install the current FIN SDK /drives folder to your Satisfactory FIN computers folder. This makes
# any file changes to these drives available ingame immediately.
#
# *IMPORTANT* You must restart any FIN comupters ingame to start executing new code.
#
# This script will back up your existing FIN computers folder every time it is run just in case
# something important gets overwritten.
###################################################################################################

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_PATH/../config"

# Copy current Satisfactory FIN computer folder into a backup folder in case anything breaks.
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
BACKUP_PATH="$BACKUPS_PATH/$TIMESTAMP"
if [ ! -d "$BACKUP_PATH" ]; then
    mkdir "$BACKUP_PATH"
fi
cp -rf "$FIN_COMPUTERS_PATH" "$BACKUP_PATH"
printf "Backed up Satisfactory FIN computers folder to:\n"
printf "  ╰──▶ ${GREEN}$BACKUP_PATH${NC}\n\n"

# Use the pull script to sync data from the Satisfactory state.
# This is important to maintain settings of computer systems set up ingame!!!
#
# TODO: Why is this conditional again? Seems like I'm doing this to prevent data files from being overwritten on push?
if [ -z "$1" ]; then
    ./pull >/dev/null 2>&1
fi

# Delete the existing computer configuration.
printf "Cleaning Satisfactory FIN computers folder...\n\n"
cd "$FIN_COMPUTERS_PATH"
find . -mindepth 1 -name \* -delete

# Publish the repo drives into the Satisfactory folder.
cp -rf $DRIVES_PATH/* "$FIN_COMPUTERS_PATH"
printf "Published drives to Satisfactory FIN computers folder:\n"
printf "  ╰──▶ ${GREEN}$FIN_COMPUTERS_PATH${NC}\n\n"

cd $PWD

echo "Done!"
