#!/bin/bash

###################################################################################################
# unassign
#
# Unassign one or more drives from their current template(s), moving them to the "unassigned" group.
###################################################################################################

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_PATH/../scripts_config"

if [ -z "$1" ]; then
    printf "Missing arguments!\n"
    printf "Usage: $0 <drive> [<drive>]...\n";
    exit 1
fi

if [ ! -d "$FIN_SDK_PATH/assigned_drives" ]; then
    printf "Nothing to do!"
    exit 0
fi

for DRIVE in "${@:1}"
do
    # If this drive was not assigned to a template, continue to the next one.
    if [ ! -f "$FIN_SDK_DIR/drives/$DRIVE/.template" ]; then
        printf "Drive ${RED}$DRIVE${NC} is not assigned to a template.\n"
        continue
    fi
    
    TEMPLATE=$( cat "$FIN_SDK_DIR/drives/$DRIVE/.template" )
    rm "$FIN_SDK_DIR/drives/$DRIVE/.template"
    rm "$FIN_SDK_PATH/assigned_drives/$TEMPLATE/$DRIVE"
    
    printf "Unassigned drive ${RED}$DRIVE${NC} from template ${GREEN}$TEMPLATE${NC}.\n"
done

printf "\nDone!\n"
