#!/bin/bash

###################################################################################################
# untag
#
# Remove a tag from one or more drives.
#
# You may use tags for whatever purpose you like. They are a freeform system to let you group
# your drives and more easily look up sets of drives that share something in common.
###################################################################################################

SCRIPT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source "$SCRIPT_PATH/../scripts_config"

if [ -z "$2" ]; then
    printf "Missing arguments!\n"
    printf "Usage: $0 <tag> <drive_uuid> [<drive_uuid>]...\n";
    exit 1
fi

for DRIVE in "${@:2}"
do
    rm -I "$SCRIPT_PATH/drives/$DRIVE/tags/$1" >/dev/null 2>&1
    printf "Removed tag ${CYAN}$1${NC} drive ${RED}$DRIVE${NC}!\n"
done

printf "\nDone!\n"
